"""Seed data for Vanilla Coffee menu — bilingual (ru / uz)."""

CATEGORIES = [
    {"id": "hot",       "name_ru": "Горячее",   "name_uz": "Issiq",       "icon": "☕", "sort_order": 1},
    {"id": "cold",      "name_ru": "Холодное",  "name_uz": "Sovuq",       "icon": "🧊", "sort_order": 2},
    {"id": "tea",       "name_ru": "Чай",       "name_uz": "Choy",        "icon": "🍵", "sort_order": 3},
    {"id": "lemonade",  "name_ru": "Лимонады",  "name_uz": "Limonadlar",  "icon": "🍋", "sort_order": 4},
    {"id": "milkshake", "name_ru": "Милкшейки", "name_uz": "Milkshake",   "icon": "🥤", "sort_order": 5},
    {"id": "fresh",     "name_ru": "Фреши",     "name_uz": "Tabiiy fresh","icon": "🍊", "sort_order": 6},
    {"id": "bakery",    "name_ru": "Выпечка",   "name_uz": "Shirinliklar","icon": "🥐", "sort_order": 7},
]


# size shortcut: (label, price, kind='ml')
def ml(label, price): return {"label": str(label), "kind": "ml", "price": price}
def pc(label, price): return {"label": label, "kind": "piece", "price": price}


PRODUCTS = [
    # ===================== HOT =====================
    {
        "id": "espresso", "category_id": "hot",
        "name_ru": "Эспрессо", "name_uz": "Espresso",
        "desc_ru": "Насыщенный концентрированный кофе с плотной кремой",
        "desc_uz": "Quyuq kremalik mazali konsentrlangan kofe",
        "ingredients_ru": ["Молотый кофе арабика 9 г", "Горячая вода 30 мл"],
        "ingredients_uz": ["Maydalangan arabika kofe 9 g", "Issiq suv 30 ml"],
        "tag_ru": "Классика", "tag_uz": "Klassika",
        "img": "https://images.unsplash.com/photo-1610889556528-9a770e32642f?w=600&q=80",
        "sizes": [ml(250, 20000), ml(350, 25000), ml(450, 45000)],
    },
    {
        "id": "americano", "category_id": "hot",
        "name_ru": "Американо", "name_uz": "Amerikano",
        "desc_ru": "Эспрессо с горячей водой — мягкий и ароматный",
        "desc_uz": "Issiq suv qo‘shilgan espresso — yumshoq va xushbo‘y",
        "ingredients_ru": ["Эспрессо 1 шот", "Горячая вода"],
        "ingredients_uz": ["Espresso 1 shot", "Issiq suv"],
        "img": "https://images.unsplash.com/photo-1494314671902-399b18174975?w=600&q=80",
        "sizes": [ml(250, 22000), ml(350, 25000), ml(450, 27000)],
    },
    {
        "id": "flat-white", "category_id": "hot",
        "name_ru": "Флэт уайт", "name_uz": "Flat White",
        "desc_ru": "Двойной эспрессо и шёлковое микропенное молоко",
        "desc_uz": "Ikki shot espresso va ipakdek mikropenali sut",
        "ingredients_ru": ["Двойной эспрессо", "Паровое молоко", "Тонкая молочная пенка"],
        "ingredients_uz": ["Ikki shot espresso", "Bug‘langan sut", "Yupqa sut ko‘pigi"],
        "tag_ru": "Хит", "tag_uz": "Hit",
        "img": "https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600&q=80",
        "sizes": [ml(250, 30000), ml(350, 35000)],
    },
    {
        "id": "cappuccino", "category_id": "hot",
        "name_ru": "Капучино", "name_uz": "Kapuchino",
        "desc_ru": "Бархатная молочная пена на эспрессо-основе",
        "desc_uz": "Espresso ustida baxmaldek sut ko‘pigi",
        "ingredients_ru": ["Эспрессо", "Паровое молоко", "Густая молочная пена"],
        "ingredients_uz": ["Espresso", "Bug‘langan sut", "Quyuq sut ko‘pigi"],
        "img": "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=600&q=80",
        "sizes": [ml(250, 27000), ml(350, 30000), ml(450, 35000)],
    },
    {
        "id": "latte", "category_id": "hot",
        "name_ru": "Латте", "name_uz": "Latte",
        "desc_ru": "Кремовый эспрессо с большим количеством молока",
        "desc_uz": "Ko‘p sut qo‘shilgan kremsimon espresso",
        "ingredients_ru": ["Эспрессо", "Паровое молоко", "Лёгкая молочная пенка"],
        "ingredients_uz": ["Espresso", "Bug‘langan sut", "Yengil sut ko‘pigi"],
        "img": "https://images.unsplash.com/photo-1561882468-9110e03e0f78?w=600&q=80",
        "sizes": [ml(250, 27000), ml(350, 30000), ml(450, 35000)],
    },
    {
        "id": "mocha", "category_id": "hot",
        "name_ru": "Мокко", "name_uz": "Mokko",
        "desc_ru": "Эспрессо, молоко и натуральный шоколад",
        "desc_uz": "Espresso, sut va tabiiy shokolad",
        "ingredients_ru": ["Эспрессо", "Молоко", "Шоколадный сироп", "Какао пудра"],
        "ingredients_uz": ["Espresso", "Sut", "Shokolad siropi", "Kakao kukuni"],
        "img": "https://images.unsplash.com/photo-1578314675229-50a503353a55?w=600&q=80",
        "sizes": [ml(250, 32000), ml(350, 35000)],
    },
    {
        "id": "raf", "category_id": "hot",
        "name_ru": "Раф", "name_uz": "Raf",
        "desc_ru": "Нежный кофе со сливками и ванильным сахаром",
        "desc_uz": "Qaymoq va vanilli shakar bilan yumshoq kofe",
        "ingredients_ru": ["Эспрессо", "Сливки 10%", "Ванильный сахар"],
        "ingredients_uz": ["Espresso", "Qaymoq 10%", "Vanilli shakar"],
        "tag_ru": "Авторский", "tag_uz": "Mualliflik",
        "img": "https://images.unsplash.com/photo-1551030173-122aabc4489c?w=600&q=80",
        "sizes": [ml(250, 30000), ml(350, 35000), ml(450, 40000)],
    },
    {
        "id": "matcha", "category_id": "hot",
        "name_ru": "Матча", "name_uz": "Matcha",
        "desc_ru": "Японский зелёный чай матча с молоком",
        "desc_uz": "Sut bilan yapon yashil matcha choyi",
        "ingredients_ru": ["Матча порошок", "Горячее молоко", "Тростниковый сахар"],
        "ingredients_uz": ["Matcha kukuni", "Issiq sut", "Qamish shakari"],
        "img": "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600&q=80",
        "sizes": [ml(250, 30000), ml(350, 35000)],
    },
    {
        "id": "cacao", "category_id": "hot",
        "name_ru": "Какао", "name_uz": "Kakao",
        "desc_ru": "Тёплое какао с молоком и нежной пенкой",
        "desc_uz": "Sut va yumshoq ko‘pikli iliq kakao",
        "ingredients_ru": ["Какао пудра", "Молоко", "Сахар"],
        "ingredients_uz": ["Kakao kukuni", "Sut", "Shakar"],
        "img": "https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=600&q=80",
        "sizes": [ml(250, 30000), ml(350, 35000)],
    },
    {
        "id": "hot-choc", "category_id": "hot",
        "name_ru": "Горячий шоколад", "name_uz": "Issiq shokolad",
        "desc_ru": "Густой шоколад из настоящего бельгийского какао",
        "desc_uz": "Belgiya kakaosidan tayyorlangan quyuq shokolad",
        "ingredients_ru": ["Бельгийский шоколад", "Молоко", "Сливки", "Корица"],
        "ingredients_uz": ["Belgiya shokoladi", "Sut", "Qaymoq", "Dolchin"],
        "tag_ru": "Premium", "tag_uz": "Premium",
        "img": "https://images.unsplash.com/photo-1517578239113-b03992dcdd25?w=600&q=80",
        "sizes": [ml(250, 40000), ml(350, 45000)],
    },

    # ===================== COLD =====================
    {
        "id": "ice-americano", "category_id": "cold",
        "name_ru": "Айс американо", "name_uz": "Muzli amerikano",
        "desc_ru": "Освежающий американо со льдом",
        "desc_uz": "Muz bilan tetiklantiruvchi amerikano",
        "ingredients_ru": ["Эспрессо 2 шот", "Холодная вода", "Лёд"],
        "ingredients_uz": ["Espresso 2 shot", "Sovuq suv", "Muz"],
        "img": "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=600&q=80",
        "sizes": [ml(450, 30000), ml(600, 33000)],
    },
    {
        "id": "ice-cappuccino", "category_id": "cold",
        "name_ru": "Айс капучино", "name_uz": "Muzli kapuchino",
        "desc_ru": "Холодный капучино с пышной пеной",
        "desc_uz": "Quyuq ko‘pikli sovuq kapuchino",
        "ingredients_ru": ["Эспрессо", "Холодное молоко", "Молочная пена", "Лёд"],
        "ingredients_uz": ["Espresso", "Sovuq sut", "Sut ko‘pigi", "Muz"],
        "img": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&q=80",
        "sizes": [ml(450, 35000), ml(600, 37000)],
    },
    {
        "id": "ice-latte", "category_id": "cold",
        "name_ru": "Айс латте", "name_uz": "Muzli latte",
        "desc_ru": "Прохладный латте с молоком и льдом",
        "desc_uz": "Sut va muz bilan salqin latte",
        "ingredients_ru": ["Эспрессо", "Холодное молоко", "Лёд"],
        "ingredients_uz": ["Espresso", "Sovuq sut", "Muz"],
        "img": "https://images.unsplash.com/photo-1517663154410-2f15a5e1e1ad?w=600&q=80",
        "sizes": [ml(450, 35000), ml(600, 40000)],
    },
    {
        "id": "ice-matcha", "category_id": "cold",
        "name_ru": "Айс Матча", "name_uz": "Muzli matcha",
        "desc_ru": "Освежающая матча со льдом",
        "desc_uz": "Muz bilan tetiklantiruvchi matcha",
        "ingredients_ru": ["Матча", "Холодное молоко", "Лёд", "Сироп по вкусу"],
        "ingredients_uz": ["Matcha", "Sovuq sut", "Muz", "Sirop (ixtiyoriy)"],
        "img": "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=600&q=80",
        "sizes": [ml(450, 35000), ml(600, 40000)],
    },
    {
        "id": "frappuccino", "category_id": "cold",
        "name_ru": "Фрапучино", "name_uz": "Frapuchino",
        "desc_ru": "Холодный кофе со взбитым молоком и сиропом",
        "desc_uz": "Sirop va ko‘pirtirilgan sut bilan sovuq kofe",
        "ingredients_ru": ["Эспрессо", "Молоко", "Лёд", "Сироп", "Взбитые сливки"],
        "ingredients_uz": ["Espresso", "Sut", "Muz", "Sirop", "Ko‘pirtirilgan qaymoq"],
        "tag_ru": "Хит", "tag_uz": "Hit",
        "img": "https://images.unsplash.com/photo-1572286258217-215cf8e9d99f?w=600&q=80",
        "sizes": [ml(450, 40000), ml(600, 45000)],
    },
    {
        "id": "bumble", "category_id": "cold",
        "name_ru": "Бамбл", "name_uz": "Bambl",
        "desc_ru": "Кофе, апельсиновый сок и лёд — освежающий микс",
        "desc_uz": "Kofe, apelsin sharbati va muz — yangi miks",
        "ingredients_ru": ["Эспрессо", "Апельсиновый сок", "Лёд"],
        "ingredients_uz": ["Espresso", "Apelsin sharbati", "Muz"],
        "img": "https://images.unsplash.com/photo-1497636577773-f1231844b336?w=600&q=80",
        "sizes": [ml(450, 35000), ml(600, 40000)],
    },
    {
        "id": "bumble-fresh", "category_id": "cold",
        "name_ru": "Бамбл на фреше", "name_uz": "Bambl freshda",
        "desc_ru": "Кофе на свежевыжатом апельсиновом фреше",
        "desc_uz": "Yangi siqilgan apelsin freshidagi kofe",
        "ingredients_ru": ["Эспрессо", "Свежевыжатый апельсин", "Лёд"],
        "ingredients_uz": ["Espresso", "Yangi siqilgan apelsin", "Muz"],
        "tag_ru": "Premium", "tag_uz": "Premium",
        "img": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&q=80",
        "sizes": [ml(450, 60000), ml(600, 70000)],
    },
    {
        "id": "espresso-tonic", "category_id": "cold",
        "name_ru": "Эспрессо тоник", "name_uz": "Espresso tonik",
        "desc_ru": "Эспрессо на тонике — освежает по-новому",
        "desc_uz": "Espresso tonik bilan — yangicha taravat",
        "ingredients_ru": ["Эспрессо", "Тоник", "Лёд", "Лайм"],
        "ingredients_uz": ["Espresso", "Tonik", "Muz", "Layim"],
        "img": "https://images.unsplash.com/photo-1606791422814-b32c705fa101?w=600&q=80",
        "sizes": [ml(450, 35000), ml(600, 40000)],
    },
    {
        "id": "energy-boom", "category_id": "cold",
        "name_ru": "Энерджи бум", "name_uz": "Energy boom",
        "desc_ru": "Энергетический коктейль с кофе для бодрого дня",
        "desc_uz": "Kuch beruvchi kofe va energetik kokteyli",
        "ingredients_ru": ["Эспрессо", "Энергетик", "Лёд", "Цитрусовый сироп"],
        "ingredients_uz": ["Espresso", "Energetik ichimlik", "Muz", "Sitrus siropi"],
        "tag_ru": "New", "tag_uz": "Yangi",
        "img": "https://images.unsplash.com/photo-1581636625402-29b2a704ef13?w=600&q=80",
        "sizes": [ml(450, 45000)],
    },

    # ===================== TEA =====================
    {
        "id": "tea-lemon", "category_id": "tea",
        "name_ru": "Чай с лимоном", "name_uz": "Limonli choy",
        "desc_ru": "Классический чёрный чай с ломтиком лимона",
        "desc_uz": "Limon tilimli klassik qora choy",
        "ingredients_ru": ["Чёрный чай", "Лимон", "Сахар"],
        "ingredients_uz": ["Qora choy", "Limon", "Shakar"],
        "img": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&q=80",
        "sizes": [ml(450, 20000), ml(600, 25000)],
    },
    {
        "id": "tea-milk", "category_id": "tea",
        "name_ru": "Чай молочный", "name_uz": "Sutli choy",
        "desc_ru": "Тёплый чай с молоком в азиатском стиле",
        "desc_uz": "Osiyo uslubidagi sutli iliq choy",
        "ingredients_ru": ["Чёрный чай", "Молоко", "Сахар"],
        "ingredients_uz": ["Qora choy", "Sut", "Shakar"],
        "img": "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=600&q=80",
        "sizes": [ml(450, 20000), ml(600, 25000)],
    },
    {
        "id": "tea-ginger", "category_id": "tea",
        "name_ru": "Чай с имбирём", "name_uz": "Zanjabilli choy",
        "desc_ru": "Согревающий чай с имбирём, мёдом и лимоном",
        "desc_uz": "Zanjabil, asal va limonli isituvchi choy",
        "ingredients_ru": ["Чёрный чай", "Имбирь", "Мёд", "Лимон"],
        "ingredients_uz": ["Qora choy", "Zanjabil", "Asal", "Limon"],
        "img": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&q=80",
        "sizes": [ml(450, 30000), ml(600, 35000)],
    },
    {
        "id": "tea-berry", "category_id": "tea",
        "name_ru": "Чай ягодный", "name_uz": "Rezavor mevali choy",
        "desc_ru": "Ароматный чай со смесью лесных ягод",
        "desc_uz": "O‘rmon mevalari aralashmasi bilan xushbo‘y choy",
        "ingredients_ru": ["Чай", "Малина", "Клубника", "Черника", "Мёд"],
        "ingredients_uz": ["Choy", "Malina", "Qulupnay", "Qora rezavor", "Asal"],
        "img": "https://images.unsplash.com/photo-1597481499845-bf2a4cf86c8b?w=600&q=80",
        "sizes": [ml(450, 30000), ml(600, 35000)],
    },
    {
        "id": "tea-fruit", "category_id": "tea",
        "name_ru": "Чай фруктовый", "name_uz": "Mevali choy",
        "desc_ru": "Освежающий чай с кусочками сезонных фруктов",
        "desc_uz": "Fasl mevalari bo‘laklari bilan tetiklantiruvchi choy",
        "ingredients_ru": ["Чай", "Апельсин", "Яблоко", "Лимон", "Мята"],
        "ingredients_uz": ["Choy", "Apelsin", "Olma", "Limon", "Yalpiz"],
        "img": "https://images.unsplash.com/photo-1568288310-69ce2dbac6ae?w=600&q=80",
        "sizes": [ml(450, 37000), ml(600, 42000)],
    },
    {
        "id": "tea-apple", "category_id": "tea",
        "name_ru": "Чай яблочный", "name_uz": "Olmali choy",
        "desc_ru": "Уютный чай с яблоком и корицей",
        "desc_uz": "Olma va dolchinli kayfiyatli choy",
        "ingredients_ru": ["Чай", "Яблоко", "Корица", "Мёд"],
        "ingredients_uz": ["Choy", "Olma", "Dolchin", "Asal"],
        "img": "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=600&q=80",
        "sizes": [ml(450, 30000), ml(600, 35000)],
    },
    {
        "id": "tea-raspberry", "category_id": "tea",
        "name_ru": "Чай малиновый", "name_uz": "Malinali choy",
        "desc_ru": "Ароматный чай с сочной малиной",
        "desc_uz": "Sersuv malinali xushbo‘y choy",
        "ingredients_ru": ["Чай", "Малина", "Мята", "Сахар"],
        "ingredients_uz": ["Choy", "Malina", "Yalpiz", "Shakar"],
        "img": "https://images.unsplash.com/photo-1563911892437-1feda0179e1b?w=600&q=80",
        "sizes": [ml(450, 30000), ml(600, 35000)],
    },

    # ===================== LEMONADES =====================
    {
        "id": "lemonade-classic", "category_id": "lemonade",
        "name_ru": "Классический лимонад", "name_uz": "Klassik limonad",
        "desc_ru": "Свежий лимонад с лимоном и мятой",
        "desc_uz": "Limon va yalpiz bilan yangi limonad",
        "ingredients_ru": ["Лимон", "Сахар", "Мята", "Газированная вода", "Лёд"],
        "ingredients_uz": ["Limon", "Shakar", "Yalpiz", "Gazlangan suv", "Muz"],
        "img": "https://images.unsplash.com/photo-1523371683702-1aaa1e74c95f?w=600&q=80",
        "sizes": [ml(450, 30000)],
    },
    {
        "id": "mojito", "category_id": "lemonade",
        "name_ru": "Мохито", "name_uz": "Mojito",
        "desc_ru": "Безалкогольный мохито с лаймом и свежей мятой",
        "desc_uz": "Layim va yangi yalpizli alkogolsiz mojito",
        "ingredients_ru": ["Лайм", "Свежая мята", "Сахарный сироп", "Газ. вода", "Лёд"],
        "ingredients_uz": ["Layim", "Yangi yalpiz", "Shakar siropi", "Gazlangan suv", "Muz"],
        "img": "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=600&q=80",
        "sizes": [ml(450, 30000)],
    },
    {
        "id": "ice-tea-fruit", "category_id": "lemonade",
        "name_ru": "Айс ти фруктовый", "name_uz": "Mevali muzli choy",
        "desc_ru": "Холодный фруктовый чай со льдом",
        "desc_uz": "Muz bilan sovuq mevali choy",
        "ingredients_ru": ["Чай", "Персик", "Лимон", "Лёд", "Сахар"],
        "ingredients_uz": ["Choy", "Shaftoli", "Limon", "Muz", "Shakar"],
        "img": "https://images.unsplash.com/photo-1556679343-c1c1c9308e4e?w=600&q=80",
        "sizes": [ml(450, 35000)],
    },
    {
        "id": "pina-colada", "category_id": "lemonade",
        "name_ru": "Пина колада", "name_uz": "Pina kolada",
        "desc_ru": "Тропический микс с ананасом и кокосом",
        "desc_uz": "Ananas va kokosli tropik miks",
        "ingredients_ru": ["Ананас", "Кокосовый сироп", "Сливки", "Лёд"],
        "ingredients_uz": ["Ananas", "Kokos siropi", "Qaymoq", "Muz"],
        "tag_ru": "Tropical", "tag_uz": "Tropik",
        "img": "https://images.unsplash.com/photo-1587223962930-cb7f31384c19?w=600&q=80",
        "sizes": [ml(450, 45000)],
    },
    {
        "id": "summer-garden", "category_id": "lemonade",
        "name_ru": "Летний сад", "name_uz": "Yozgi bog‘",
        "desc_ru": "Освежающий микс с ягодами и базиликом",
        "desc_uz": "Rezavor va rayhonli tetiklantiruvchi miks",
        "ingredients_ru": ["Лесные ягоды", "Базилик", "Лимон", "Газ. вода", "Лёд"],
        "ingredients_uz": ["O‘rmon mevalari", "Rayhon", "Limon", "Gazlangan suv", "Muz"],
        "img": "https://images.unsplash.com/photo-1546171753-97d7676e4602?w=600&q=80",
        "sizes": [ml(450, 40000)],
    },

    # ===================== MILKSHAKES =====================
    {
        "id": "milkshake-classic", "category_id": "milkshake",
        "name_ru": "Классический милкшейк", "name_uz": "Klassik milkshake",
        "desc_ru": "Ванильный молочный коктейль с пломбиром",
        "desc_uz": "Plombir bilan vanilli sutli kokteyl",
        "ingredients_ru": ["Ванильное мороженое", "Молоко", "Ванильный сироп"],
        "ingredients_uz": ["Vanilli muzqaymoq", "Sut", "Vanilli sirop"],
        "img": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&q=80",
        "sizes": [ml(450, 30000), ml(600, 35000)],
    },
    {
        "id": "snickers-shake", "category_id": "milkshake",
        "name_ru": "Сникерс милкшейк", "name_uz": "Snickers milkshake",
        "desc_ru": "Шоколад, карамель, арахис и мороженое",
        "desc_uz": "Shokolad, karamel, yeryong‘oq va muzqaymoq",
        "ingredients_ru": ["Мороженое", "Молоко", "Шоколадный сироп", "Карамель", "Арахис"],
        "ingredients_uz": ["Muzqaymoq", "Sut", "Shokolad siropi", "Karamel", "Yeryong‘oq"],
        "tag_ru": "Хит", "tag_uz": "Hit",
        "img": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
        "sizes": [ml(450, 40000), ml(600, 45000)],
    },
    {
        "id": "coconut-shake", "category_id": "milkshake",
        "name_ru": "Кокосовый милкшейк", "name_uz": "Kokosli milkshake",
        "desc_ru": "Тропический милкшейк с кокосом",
        "desc_uz": "Kokosli tropik milkshake",
        "ingredients_ru": ["Мороженое", "Молоко", "Кокосовая стружка", "Кокосовый сироп"],
        "ingredients_uz": ["Muzqaymoq", "Sut", "Kokos qirindisi", "Kokos siropi"],
        "img": "https://images.unsplash.com/photo-1502741126161-b048400d085d?w=600&q=80",
        "sizes": [ml(450, 40000), ml(600, 45000)],
    },
    {
        "id": "berry-shake", "category_id": "milkshake",
        "name_ru": "Ягодный милкшейк", "name_uz": "Rezavorli milkshake",
        "desc_ru": "Молочный коктейль с лесными ягодами",
        "desc_uz": "O‘rmon mevalari bilan sutli kokteyl",
        "ingredients_ru": ["Мороженое", "Молоко", "Лесные ягоды", "Сахар"],
        "ingredients_uz": ["Muzqaymoq", "Sut", "O‘rmon mevalari", "Shakar"],
        "img": "https://images.unsplash.com/photo-1553787499-6f9133860278?w=600&q=80",
        "sizes": [ml(450, 40000), ml(600, 45000)],
    },
    {
        "id": "oreo-shake", "category_id": "milkshake",
        "name_ru": "Орео милкшейк", "name_uz": "Oreo milkshake",
        "desc_ru": "Шоколадный шейк с печеньем Oreo",
        "desc_uz": "Oreo pechenesi bilan shokoladli shake",
        "ingredients_ru": ["Мороженое", "Молоко", "Печенье Oreo", "Шоколадный сироп"],
        "ingredients_uz": ["Muzqaymoq", "Sut", "Oreo pechenesi", "Shokolad siropi"],
        "tag_ru": "Premium", "tag_uz": "Premium",
        "img": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&q=80",
        "sizes": [ml(450, 42000), ml(600, 47000)],
    },
    {
        "id": "banana-shake", "category_id": "milkshake",
        "name_ru": "Банановый милкшейк", "name_uz": "Bananli milkshake",
        "desc_ru": "Нежный коктейль со свежим бананом",
        "desc_uz": "Yangi banan bilan yumshoq kokteyl",
        "ingredients_ru": ["Мороженое", "Молоко", "Свежий банан"],
        "ingredients_uz": ["Muzqaymoq", "Sut", "Yangi banan"],
        "img": "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=600&q=80",
        "sizes": [ml(450, 40000), ml(600, 45000)],
    },
    {
        "id": "choc-shake", "category_id": "milkshake",
        "name_ru": "Шоколадный милкшейк", "name_uz": "Shokoladli milkshake",
        "desc_ru": "Густой шоколадный шейк для сладкоежек",
        "desc_uz": "Shirinlik ishqibozlari uchun quyuq shokoladli shake",
        "ingredients_ru": ["Мороженое", "Молоко", "Шоколад", "Какао"],
        "ingredients_uz": ["Muzqaymoq", "Sut", "Shokolad", "Kakao"],
        "img": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&q=80",
        "sizes": [ml(450, 40000), ml(600, 45000)],
    },

    # ===================== FRESH =====================
    {
        "id": "fresh-apple", "category_id": "fresh",
        "name_ru": "Яблоко", "name_uz": "Olma",
        "desc_ru": "Свежевыжатый яблочный сок",
        "desc_uz": "Yangi siqilgan olma sharbati",
        "ingredients_ru": ["100% свежее яблоко"],
        "ingredients_uz": ["100% yangi olma"],
        "img": "https://images.unsplash.com/photo-1576673442511-7e39b6545c87?w=600&q=80",
        "sizes": [ml(450, 35000), ml(600, 45000)],
    },
    {
        "id": "fresh-carrot", "category_id": "fresh",
        "name_ru": "Морковь", "name_uz": "Sabzi",
        "desc_ru": "Сладкий морковный фреш — витамин для кожи",
        "desc_uz": "Shirin sabzi freshi — teri uchun vitamin",
        "ingredients_ru": ["100% свежая морковь"],
        "ingredients_uz": ["100% yangi sabzi"],
        "img": "https://images.unsplash.com/photo-1597740049799-5ba6f1f49531?w=600&q=80",
        "sizes": [ml(450, 30000), ml(600, 45000)],
    },
    {
        "id": "fresh-orange", "category_id": "fresh",
        "name_ru": "Апельсин", "name_uz": "Apelsin",
        "desc_ru": "Освежающий апельсиновый фреш",
        "desc_uz": "Tetiklantiruvchi apelsin freshi",
        "ingredients_ru": ["100% свежий апельсин"],
        "ingredients_uz": ["100% yangi apelsin"],
        "tag_ru": "Vitamin C", "tag_uz": "Vitamin C",
        "img": "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=600&q=80",
        "sizes": [ml(450, 65000), ml(600, 80000)],
    },
    {
        "id": "fresh-orange-carrot", "category_id": "fresh",
        "name_ru": "Апельсин + морковь", "name_uz": "Apelsin + sabzi",
        "desc_ru": "Микс из апельсина и моркови",
        "desc_uz": "Apelsin va sabzi miksi",
        "ingredients_ru": ["Апельсин", "Морковь"],
        "ingredients_uz": ["Apelsin", "Sabzi"],
        "img": "https://images.unsplash.com/photo-1622597467836-f3e6707e1191?w=600&q=80",
        "sizes": [ml(450, 50000), ml(600, 75000)],
    },
    {
        "id": "fresh-apple-carrot", "category_id": "fresh",
        "name_ru": "Яблоко + морковь", "name_uz": "Olma + sabzi",
        "desc_ru": "Лёгкий и сбалансированный микс",
        "desc_uz": "Yengil va muvozanatli miks",
        "ingredients_ru": ["Яблоко", "Морковь"],
        "ingredients_uz": ["Olma", "Sabzi"],
        "img": "https://images.unsplash.com/photo-1622597467836-f3e6707e1191?w=600&q=80",
        "sizes": [ml(450, 45000), ml(600, 55000)],
    },
    {
        "id": "fresh-apple-orange", "category_id": "fresh",
        "name_ru": "Яблоко + апельсин", "name_uz": "Olma + apelsin",
        "desc_ru": "Освежающий цитрусовый микс",
        "desc_uz": "Tetiklantiruvchi sitrus miksi",
        "ingredients_ru": ["Яблоко", "Апельсин"],
        "ingredients_uz": ["Olma", "Apelsin"],
        "img": "https://images.unsplash.com/photo-1622597467836-f3e6707e1191?w=600&q=80",
        "sizes": [ml(450, 60000), ml(600, 75000)],
    },
    {
        "id": "fresh-mix", "category_id": "fresh",
        "name_ru": "Яблоко + морковь + апельсин", "name_uz": "Olma + sabzi + apelsin",
        "desc_ru": "Витаминный заряд из трёх фруктов",
        "desc_uz": "Uchta meva-sabzavotdan vitamin zaryadi",
        "ingredients_ru": ["Яблоко", "Морковь", "Апельсин"],
        "ingredients_uz": ["Olma", "Sabzi", "Apelsin"],
        "tag_ru": "Mix", "tag_uz": "Miks",
        "img": "https://images.unsplash.com/photo-1622597467836-f3e6707e1191?w=600&q=80",
        "sizes": [ml(450, 55000), ml(600, 75000)],
    },

    # ===================== BAKERY =====================
    {
        "id": "apple-pie", "category_id": "bakery",
        "name_ru": "Яблочный пирог", "name_uz": "Olmali pirog",
        "desc_ru": "Домашний пирог с яблоками и корицей",
        "desc_uz": "Olma va dolchinli uy pirogi",
        "ingredients_ru": ["Песочное тесто", "Яблоки", "Корица", "Сахар", "Сливочное масло"],
        "ingredients_uz": ["Qum xamir", "Olma", "Dolchin", "Shakar", "Sariyog‘"],
        "img": "https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=600&q=80",
        "sizes": [pc("1 шт / 1 dona", 28000)],
    },
    {
        "id": "cherry-pie", "category_id": "bakery",
        "name_ru": "Вишнёвый пирог", "name_uz": "Olchali pirog",
        "desc_ru": "Сочный пирог с ароматной вишней",
        "desc_uz": "Xushbo‘y olcha bilan sersuv pirog",
        "ingredients_ru": ["Песочное тесто", "Вишня", "Сахар", "Крахмал"],
        "ingredients_uz": ["Qum xamir", "Olcha", "Shakar", "Kraxmal"],
        "img": "https://images.unsplash.com/photo-1621743478914-cc8a86d7e7b5?w=600&q=80",
        "sizes": [pc("1 шт / 1 dona", 28000)],
    },
    {
        "id": "cookies-mix", "category_id": "bakery",
        "name_ru": "Ассорти печенье", "name_uz": "Pechene assorti",
        "desc_ru": "Микс из разных видов домашнего печенья",
        "desc_uz": "Turli xil uy pechenelari aralashmasi",
        "ingredients_ru": ["Овсяное, шоколадное и молочное печенье"],
        "ingredients_uz": ["Sulili, shokoladli va sutli pechene"],
        "img": "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&q=80",
        "sizes": [pc("1 шт / 1 dona", 35000)],
    },
    {
        "id": "brownie", "category_id": "bakery",
        "name_ru": "Брауни", "name_uz": "Brauni",
        "desc_ru": "Шоколадный десерт с насыщенным вкусом",
        "desc_uz": "To‘yintirilgan ta'mli shokoladli desert",
        "ingredients_ru": ["Тёмный шоколад", "Сливочное масло", "Яйца", "Мука", "Сахар"],
        "ingredients_uz": ["Tund shokolad", "Sariyog‘", "Tuxum", "Un", "Shakar"],
        "tag_ru": "Хит", "tag_uz": "Hit",
        "img": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&q=80",
        "sizes": [pc("1 шт / 1 dona", 20000)],
    },
    {
        "id": "anthill", "category_id": "bakery",
        "name_ru": "Муравейник", "name_uz": "Chumolitepa",
        "desc_ru": "Классический торт со сгущёнкой и орехами",
        "desc_uz": "Quyultirilgan sut va yong‘oqli klassik tort",
        "ingredients_ru": ["Песочное тесто", "Варёная сгущёнка", "Грецкий орех"],
        "ingredients_uz": ["Qum xamir", "Qaynatilgan quyultirilgan sut", "Yong‘oq"],
        "img": "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&q=80",
        "sizes": [pc("1 шт / 1 dona", 35000)],
    },
    {
        "id": "milk-cookies", "category_id": "bakery",
        "name_ru": "Печеньки молочные", "name_uz": "Sutli pechene",
        "desc_ru": "Нежное песочное печенье с молочным кремом",
        "desc_uz": "Sutli kremli yumshoq qum pechene",
        "ingredients_ru": ["Песочное тесто", "Молочный крем", "Ваниль"],
        "ingredients_uz": ["Qum xamir", "Sutli krem", "Vanil"],
        "img": "https://images.unsplash.com/photo-1568051243858-533a607809a5?w=600&q=80",
        "sizes": [pc("1 шт / 1 dona", 28000)],
    },
    {
        "id": "choc-cookies", "category_id": "bakery",
        "name_ru": "Печеньки шоколадные", "name_uz": "Shokoladli pechene",
        "desc_ru": "Хрустящее печенье с кусочками шоколада",
        "desc_uz": "Shokolad bo‘laklari bilan qarsillaydigan pechene",
        "ingredients_ru": ["Мука", "Сливочное масло", "Тёмный шоколад", "Сахар"],
        "ingredients_uz": ["Un", "Sariyog‘", "Tund shokolad", "Shakar"],
        "img": "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&q=80",
        "sizes": [pc("1 шт / 1 dona", 28000)],
    },
    {
        "id": "nuts-condensed", "category_id": "bakery",
        "name_ru": "Орешки со сгущёнкой", "name_uz": "Quyultirilgan sutli yong‘oqchalar",
        "desc_ru": "Классический советский десерт",
        "desc_uz": "Klassik sovet deserti",
        "ingredients_ru": ["Песочное тесто", "Варёная сгущёнка", "Сливочное масло"],
        "ingredients_uz": ["Qum xamir", "Qaynatilgan quyultirilgan sut", "Sariyog‘"],
        "img": "https://images.unsplash.com/photo-1612203985729-70726954388c?w=600&q=80",
        "sizes": [pc("1 шт / 1 dona", 28000)],
    },
    {
        "id": "trifle", "category_id": "bakery",
        "name_ru": "Трайфл", "name_uz": "Trayfl",
        "desc_ru": "Многослойный десерт с кремом и ягодами",
        "desc_uz": "Krem va rezavorli ko‘p qatlamli desert",
        "ingredients_ru": ["Бисквит", "Сливочный крем", "Свежие ягоды"],
        "ingredients_uz": ["Biskvit", "Sutli krem", "Yangi rezavorlar"],
        "tag_ru": "Premium", "tag_uz": "Premium",
        "img": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&q=80",
        "sizes": [pc("1 шт / 1 dona", 35000)],
    },
    {
        "id": "croissant", "category_id": "bakery",
        "name_ru": "Круассан", "name_uz": "Kruassan",
        "desc_ru": "Французский слоёный круассан",
        "desc_uz": "Fransuz qatlamli kruassan",
        "ingredients_ru": ["Слоёное тесто", "Сливочное масло", "Сахарная пудра"],
        "ingredients_uz": ["Qatlamli xamir", "Sariyog‘", "Shakar kukuni"],
        "tag_ru": "Свежий", "tag_uz": "Yangi",
        "img": "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80",
        "sizes": [pc("1 шт / 1 dona", 27000)],
    },
    {
        "id": "muffin", "category_id": "bakery",
        "name_ru": "Маффин", "name_uz": "Maffin",
        "desc_ru": "Воздушный маффин на каждый день",
        "desc_uz": "Har kun uchun yengil maffin",
        "ingredients_ru": ["Мука", "Сахар", "Яйца", "Молоко", "Шоколадная крошка"],
        "ingredients_uz": ["Un", "Shakar", "Tuxum", "Sut", "Shokolad qirindisi"],
        "img": "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=600&q=80",
        "sizes": [pc("1 шт / 1 dona", 25000)],
    },
    {
        "id": "macaron", "category_id": "bakery",
        "name_ru": "Макарон", "name_uz": "Makaron",
        "desc_ru": "Французское пирожное-безе",
        "desc_uz": "Fransuz beze tortchasi",
        "ingredients_ru": ["Миндальная мука", "Сахарная пудра", "Белки", "Крем"],
        "ingredients_uz": ["Bodom uni", "Shakar kukuni", "Tuxum oqi", "Krem"],
        "img": "https://images.unsplash.com/photo-1558326567-98ae2405596b?w=600&q=80",
        "sizes": [pc("1 шт / 1 dona", 8000)],
    },
]
